"""empty message

Revision ID: 464915f269e0
Revises: 408a1dab6720
Create Date: 2020-06-25 13:37:13.465878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464915f269e0'
down_revision = '408a1dab6720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('volunteer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'volunteer_id')
    # ### end Alembic commands ###
