"""empty message

Revision ID: 569668820d99
Revises: f07663c83338
Create Date: 2020-06-26 16:02:16.126220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569668820d99'
down_revision = 'f07663c83338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'author')
    # ### end Alembic commands ###
